version: '3.4'

services:
  userservice.host:
    image: ${DOCKER_REGISTRY-}userservicehost
    build:
      context: .
      dockerfile: UserService.Host/Dockerfile
    ports:
      - "10001:80"
    links:
      - user_database
    depends_on:
      - user_database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - CONNECTION_STRING=Host=user_database;Username=postgres;Password=password;Database=user_db;

  user_database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=User_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - user-db-volume:/var/lib/postgresql/data
volumes:
  user-db-volume:
    driver: local  
